# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160406_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='about',
            field=models.TextField(blank=True, verbose_name='Sobre o Curso'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descriçao Simples'),
        ),
    ]
